### ISSUE TITLE
Cannot add Data Links

### ISSUE THREAD

**Issue by curvaton** [jackw/heywesty-trafficlight-panel#27]
Hello,

Thanks for your plugin ! 

I am currently replacing the Angular Traffic Lights plugin in our dashboards by yours. I am able to display the data I want, the way I want, from an OpenSearch Data Source:
<img width="1657" alt="Capture d’écran 2024-08-28 à 18 11 15" src="https://github.com/user-attachments/assets/4fc07f05-38ae-47b5-85c7-43734bc4bad3">

I would like to add data links to redirect to another dashboard.

When I click on the "Add link" button I get this formular
<img width="811" alt="Capture d’écran 2024-08-28 à 18 12 56" src="https://github.com/user-attachments/assets/0e6970d8-f3c6-4ea0-aacf-129222310d69">
But when I click on "Save" I get this error:
<img width="1671" alt="Capture d’écran 2024-08-28 à 18 14 15" src="https://github.com/user-attachments/assets/fcd432ff-9929-4f74-9cf4-e6e8a3b669d9">

I am running the dockerised Grafana 11.1.4 version. 

I gave an example data link I would like to create but what I am looking for is to have a link for each traffic light that a viewer could click on to be redirected to a specific dashboard depending on the value of the data which is displayed. 

Thanks for your help !

**Comment by jackw** [comment]
@curvaton thanks for raising this.

I tried to reproduce your issue locally and I cannot. The feature isn't custom to my panel, it's part of the Grafana codebase. You can find [the docs here](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-data-links/). 

As for the error - could you pass me the panel JSON and panel data please? They can be accessed by clicking inspect in the panel menu. If I have those I might have a better chance of reproducing the issue.

![image](https://github.com/user-attachments/assets/b530fa3b-90cc-445a-a7f4-80ebc7e64159)

**Comment by curvaton** [comment]
Hello,

Thanks for the investigation. Since this happens in a production environment, to give the panel json and panel data I have to prepare some mock data and reproduce in a local environment and then send it to you. I'll try to do this as fast as I can.

Thanks again.

**Comment by curvaton** [comment]
Hello,

I could finally spend some time to produce mock data for reproducing the issue. I could reproduce it running in a local docker-compose environment with an opensearch datasource and grafana services (version 11.1.4).

Here are the data and panels in json format as requested. 

[data.json](https://github.com/user-attachments/files/17188035/data.json)
[panel.json](https://github.com/user-attachments/files/17188036/panel.json)

Hope this helps.

**Comment by jackw** [comment]
>Here are the data and panels in json format as requested.

Thanks for taking the time @curvaton. I'll try and repro it and get back to you soon.

**Comment by jackw** [comment]
@curvaton A fix for this should now be available in [version 0.5.1](https://grafana.com/grafana/plugins/heywesty-trafficlight-panel/). 🚀 

Please reply here if you that's not the case.
