### ISSUE TITLE
Wishlist: Option to reverse traffic light colors (aka thresholds)

### ISSUE THREAD

**Issue by fgrandel** [jackw/heywesty-trafficlight-panel#3]
First of all: Thanks for this beautiful visualization. Love it.

There is one minor feature I'm missing: Currently you're mapping through the thresholds in one direction only. As grafana auto-sorts thresholds, this means that if you have lowest values being "green" then the green light will be uppermost.

This is confusing - especially to visually impaired users who cannot distinguish red and green.

It would be great if you implemented a simple switch that allowed one to reverse the order of traffic lights colors.

**Comment by jackw** [comment]
Hey @fgrandel, thanks for this suggestion it sounds like I great addition! 

Let me know if you'd like to implement it (I'm more than happy to see external contributions to this project) otherwise I'll look at doing it as soon as I can find the time. 👍

**Comment by fgrandel** [comment]
Hi Jack,

I'd love to contribute and it's an easy change anyway, but I'll start a 
new job on the 2nd of April and have to prepare.

Sorry.

And again thanks for your great plugin. :-) I'm using it to track CO2, 
temperature and humidity limits at home.

Kind regards,

Florian

Am 27.03.24 um 11:34 schrieb Jack Westbrook:

**Comment by drjoeward** [comment]
I would like to also add a vote to invert.   I use grafana to monitor a multitude of science instruments in my labs and the bulk of them are good to go when the value is 0  but 1 when something is in alarm.   being upside down is a bit disconcerting.  

on the order of wishlists,  it would be great to have the option to not display the value,  but alos leave the legend.   with the old traffic lights i used the legend to stipulate what instrument (i.e. i have 20 of the same thing and just create one panel with a repeate)  but having the small 0 or 1 showing is a bit messy.
