### ISSUE TITLE
Deadlink buymeacoffee

### ISSUE THREAD

**Issue by idrissneumann** [jackw/heywesty-trafficlight-panel#32]
Hi.

This link is returning 404: [buymeacoffee.com/jackwestbrook](https://buymeacoffee.com/jackwestbrook)

<img width="1202" alt="Screenshot 2024-09-20 at 16 59 48" src="https://github.com/user-attachments/assets/3cae8913-1f5b-4916-9a31-30e00d534dee">

I wanted to buy you a coffee because you saved us with your amazing work here ❤️

Idriss

**Comment by jackw** [comment]
> I wanted to buy you a coffee because you saved us with your amazing work here ❤️

Hey @idrissneumann,

Thanks for the kind words and for letting me know, really appreciate it. I'd forgotten to finish setting up the account. 🤦 

[The link](https://buymeacoffee.com/jackwestbrook) should be working now. ❤️
